---
title: "R Notebook"
output: html_notebook
---
```{r}
library("rvest")
url <- "https://www.havocscope.com/black-market-prices/heroin-prices/"
raw_data <- url %>%
  read_html() %>%
  html_nodes("li") %>%
  html_text()
```

```{r}
raw_data <- raw_data[8:79]
raw_data[5] <- "Australia$50.4 per gram"
raw_data[8] <- "USA$200 per gram"
raw_data[49] <- "Jordan$35.1 per gram"
raw_data <- unlist(raw_data)
raw_data <- strsplit(raw_data, ' per', fixed = TRUE) %>%
  lapply("[[", 1) %>%
  unlist %>%
  strsplit("$", fixed = TRUE)
```

```{r}
nations <- lapply(raw_data, "[[", 1) %>% unlist
nations
heroin_price <- lapply(raw_data, "[", 2) %>% 
  unlist %>%
  as.numeric
heroin_price <- heroin_price[order(heroin_price, decreasing = TRUE)]
nations <- lapply(raw_data, "[[", 1) %>% 
  unlist %>%
  factor(levels = nations[order(heroin_price, decreasing = TRUE)])
dt <- data.frame(nations, heroin_price, heroin_price / 200)
names(dt) <- c("Name", "Price", "Local Price/US Price")
dt
```

```{r}
# to draw a bar plot
top20 <- dt[1:20,]
`LocalPrice/USPrice` = dt$`Local Price/US Price`[1:20]
library(ggplot2)
bar <- ggplot(data = top20, aes(x = top20$Name, y=top20$`Price`)) +
  geom_bar(stat="identity", position="dodge", aes(fill=`Local Price/US Price`)) + 
  xlab("Nation") +  ylab("Price (USD per gram)") + ggtitle("Top 20 Heroine Price") +
  geom_hline(yintercept = top20$`Price`[8], linetype="dashed", color = "red") + 
  geom_text(aes(-1, top20$`Price`[8],label = "USA", vjust = -1), color = "red") + 
  coord_flip()
bar
ggsave(plot = bar, file = "top20 Heroine Price.png", device = "png", width = 6, 
    height = 6, units = "in", dpi = 600, family = "ArialMT")
```

```{r}
library(ggplot2)
library(dplyr)

WorldData <- map_data('world')
WorldData %>% filter(region != "Antarctica") -> WorldData
WorldData <- fortify(WorldData)
p <- ggplot()
p <- p + geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)
p <- p + geom_map(data=dt, map=WorldData, aes(fill=Price, map_id=Name), colour="#7f7f7f", size=0.5) + 
  scale_fill_continuous(low="thistle2", high="darkred", guide="colorbar") + 
  ggtitle("Heroine Prices in Different Countries (USD per gram)") +
  xlab("longtitude") +  ylab("latitude")
p
ggsave(plot = p, file = "Heroine Price World Map.png", device = "png", width = 11, 
    height = 6, units = "in", dpi = 600, family = "ArialMT")
```
