---
title: "R Notebook"
output: html_notebook
---
```{r}
a <- list.files(path = "./user1-13", recursive = TRUE)
data <- read.csv(file = "./user1-13/user1/1kg/1_2/myo1_EMG.csv", header=T, sep=",")
data
```
```{r}
library(stringr)
library(ggplot2)
library(clampSeg)
for(i in a[1:2])
{
  if(str_detect(i, "_EMG.csv") & !(str_detect(i, "lak")))
    data <- read.csv(file = paste("./user1-13/", i, sep = ""), header=T, sep=",")
    # print(data)
    # b = lowpassFilter(param = as.list(data$C1), sr = 1, len = NULL, shift = 0.5)
    plot <- ggplot(data = data, mapping = aes(x = timestamp, y = C1))
    plot <- plot + geom_line()
    show(plot)
}
ggsave("EMG_raw.png", plot = last_plot())

```
```{r}
library(wavethresh)
y <- c(3,6,4,3,5,1,3,5)
ywd <- wd(data$C1)
ywd
```
```{r}
X = vector()
Y = vector()
for(i in a)
{
  if(str_detect(i, "_EMG.csv") & !(str_detect(i, "lak")))
    data <- read.csv(file = paste("./user1-13/", i, sep = ""), header=T, sep=",")
    for(i in 1:length(data$C4))
      if(i + 200 < length(data$C4))
        X = append(X, c(c(data$C4[i:i + 200])))
        Y = append(Y, as.integer(str_remove_all(strsplit(a[i], '/')[-3]), "kg")), '\'))
        print(Y)
    # print(data)
    # b = lowpassFilter(param = as.list(data$C1), sr = 1, len = NULL, shift = 0.5)
    
}
```

```{r}
library(keras)

# Setup input

# input <- layer_input(
#   shape = list(NULL),
#   dtype = "int32",
#   name = "input"
# )

# Model layers

# model <- keras_model_sequential() 
# model %>% 
#   layer_dense(units = 256, activation = 'relu', input_shape = c(784)) %>%
#   layer_dropout(rate = 0.4) %>% 
#   layer_dense(units = 128, activation = 'relu') %>%
#   layer_dropout(rate = 0.3) %>%
#   layer_dense(units = 10, activation = 'softmax')

model <- keras_model_sequential()  
model %>%
  layer_input(shape = list(NULL), dtype = "int32", name = "input" ) %>%
  
  bidirectional(layer_lstm(units = 200, dropout = 0.25, recurrent_dropout = 0.25, return_sequences = FALSE, name = "lstm")) %>%
  
  lstm %>% bidirectional(layer_lstm(units = 200, dropout = 0.25, recurrent_dropout = 0.25, return_sequences = FALSE, name = "lstm2")) %>%
  
  layer_dense(units = 1, activation = "sigmoid", name = "predictions") %>%
  

# lstm <- bidirectional(layer_lstm(units = 200, dropout = 0.25, recurrent_dropout = 0.25, return_sequences = FALSE, name = "lstm"))

# lstm2 <- lstm %>% bidirectional(layer_lstm(units = 200, dropout = 0.25, recurrent_dropout = 0.25, return_sequences = FALSE, name = "lstm2"))

# predictions <- lstm2 %>% 
#     layer_dense(units = 1, activation = "sigmoid", name = "predictions")


# Bring model together

# model <- keras_model(input, predictions)

# Compile

model %>% compile(
  optimizer = optimizer_adam(),
  loss = "mean_square_error",
  metrics = "binary_accuracy"
)

# Train model 

history <- model %>% fit(
  X,
  Y,
  batch_size = 200,
  validation_data = list(x_val, y_val),
  epochs = 35,
  view_metrics = FALSE,
  verbose = 0
)
```

```{r}
c <- str_remove_all("123123", "1")
as.integer(c)
```


